// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-fullstack/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) CreateUser(ctx context.Context, newUser domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, newUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, newUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser domain.User
func (_e *MockIUserRepository_Expecter) CreateUser(ctx interface{}, newUser interface{}) *MockIUserRepository_CreateUser_Call {
	return &MockIUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, newUser)}
}

func (_c *MockIUserRepository_CreateUser_Call) Run(run func(ctx context.Context, newUser domain.User)) *MockIUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_CreateUser_Call) Return(user *domain.User, err error) *MockIUserRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, newUser domain.User) (*domain.User, error)) *MockIUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserAdmin provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) CreateUserAdmin(ctx context.Context, newUser domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, newUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserAdmin")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, newUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_CreateUserAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserAdmin'
type MockIUserRepository_CreateUserAdmin_Call struct {
	*mock.Call
}

// CreateUserAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser domain.User
func (_e *MockIUserRepository_Expecter) CreateUserAdmin(ctx interface{}, newUser interface{}) *MockIUserRepository_CreateUserAdmin_Call {
	return &MockIUserRepository_CreateUserAdmin_Call{Call: _e.mock.On("CreateUserAdmin", ctx, newUser)}
}

func (_c *MockIUserRepository_CreateUserAdmin_Call) Run(run func(ctx context.Context, newUser domain.User)) *MockIUserRepository_CreateUserAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_CreateUserAdmin_Call) Return(user *domain.User, err error) *MockIUserRepository_CreateUserAdmin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_CreateUserAdmin_Call) RunAndReturn(run func(ctx context.Context, newUser domain.User) (*domain.User, error)) *MockIUserRepository_CreateUserAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetUser(ctx context.Context, username string) (*domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockIUserRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserRepository_Expecter) GetUser(ctx interface{}, username interface{}) *MockIUserRepository_GetUser_Call {
	return &MockIUserRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, username)}
}

func (_c *MockIUserRepository_GetUser_Call) Run(run func(ctx context.Context, username string)) *MockIUserRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetUser_Call) Return(user *domain.User, err error) *MockIUserRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, error)) *MockIUserRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockIUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIUserRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockIUserRepository_GetUserByID_Call {
	return &MockIUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockIUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, id int64)) *MockIUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetUserByID_Call) Return(user *domain.User, err error) *MockIUserRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *MockIUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}
