// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-fullstack/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function for the type MockIUserService
func (_mock *MockIUserService) AuthenticateUser(ctx context.Context, username string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type MockIUserService_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockIUserService_Expecter) AuthenticateUser(ctx interface{}, username interface{}, password interface{}) *MockIUserService_AuthenticateUser_Call {
	return &MockIUserService_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", ctx, username, password)}
}

func (_c *MockIUserService_AuthenticateUser_Call) Run(run func(ctx context.Context, username string, password string)) *MockIUserService_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserService_AuthenticateUser_Call) Return(user *domain.User, err error) *MockIUserService_AuthenticateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_AuthenticateUser_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (*domain.User, error)) *MockIUserService_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockIUserService
func (_mock *MockIUserService) CreateUser(ctx context.Context, user domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockIUserService_Expecter) CreateUser(ctx interface{}, user interface{}) *MockIUserService_CreateUser_Call {
	return &MockIUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockIUserService_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockIUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserService_CreateUser_Call) Return(user1 *domain.User, err error) *MockIUserService_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockIUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (*domain.User, error)) *MockIUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}
